### ISSUE TITLE
Setting OpenCL path not working

### ISSUE THREAD

**Issue by htzheng** [IntelVCL/dcflow#2]
export INTELOCLSDKROOT or CUDA_PATH or AMDAPPSDKROOD is currently not working, as the compiler can't find the path of opencl (fatal error: CL/cl.hpp: No such file or directory)

A workaround is to set a global include path by export CPATH path/to/cl/include

**Comment by jia-xu** [comment]
Please export the path before running cmake.

We tested with both Ubuntu 14.04 and Ubuntu 16.04, and it works for both settings.

**Comment by htzheng** [comment]
Thanks! For some reason I couldn't make it work on my Ubuntu 16.04 system by following the instruction, but exporting CPATH before cmake solves my problem.
