### ISSUE TITLE
Cannot run demo.m successfully

### ISSUE THREAD

**Issue by lijiaman** [IntelVCL/dcflow#4]
Hi,
I have compiled caffe (the version mentioned in this repo) successfully, and can also make matcaffe successfully, and build dcflow successfully following the instructions. However, I got the error below when I ran demo.m. I'm using matlab-R2016a version.
Invalid MEX-file '/home/project/dcflow/matlab/dcflow_mex.mexa64':
/home/project/dcflow/matlab/dcflow_mex.mexa64: undefined symbol: clGetProgramBuildInfo
Could you help? Thanks!

**Comment by lijiaman** [comment]
Just solved the issue.

**Comment by jia-xu** [comment]
Good to hear ;) We have not seen this issue before. Can you also share solution here? It will be helpful for future users.

**Comment by lijiaman** [comment]
when do cmake, use:
cmake -DOpenCL_LIBRARY=/dir/cuda-8.0/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIRS=/dir/cuda-8.0/include ..
Before, I set the first to /dir/cuda-8.0/lib64, and it gave me a warning, saying it's a directory. After changing it to a *.so, it works. : )
Btw, will you release the codes for training? That would be very useful if you can provide the complete codes. ;) Thanks!
